Repository KOSA-DDABONG/back-end, pull requests merged in 2024-08, with the labels that each got.

#76 [Bug] CORS 에러 해결
  build.gradle
  src/main/java/com/ddabong/TripFlow/config/CorsMvcConfig.java
  src/main/java/com/ddabong/TripFlow/config/SecurityConfig.java
Labels: bug

#77 [Bug] CORS 에러 해결
  src/main/java/com/ddabong/TripFlow/config/CorsMvcConfig.java
Labels: bug

#79 [Refactor] 개발시 CORS 허용
  src/main/java/com/ddabong/TripFlow/config/CorsMvcConfig.java
Labels: Refactor

#80 [Refactor] json 형식으로 파라미터 받기
  src/main/java/com/ddabong/TripFlow/member/controller/JoinController.java
  src/main/java/com/ddabong/TripFlow/member/dto/LoginRequestDTO.java
  src/main/java/com/ddabong/TripFlow/member/jwt/LoginFilter.java
Labels: Refactor

#88 [Refactor] 생성자 주입 방식 -> 빈 주입 방식 변경
  src/main/java/com/ddabong/TripFlow/member/controller/JoinController.java
  src/main/java/com/ddabong/TripFlow/member/service/IMemberService.java
  src/main/java/com/ddabong/TripFlow/member/service/MemberService.java
Labels: Refactor

#89 [Test] mg jang
  README.md
Labels: Refactor

#90 [Testing] 'MG JANG'
  README.md
Labels: Refactor

#91 [Refactor] 개발 테스트 경로 허용
  src/main/java/com/ddabong/TripFlow/config/SecurityConfig.java
Labels: Refactor

#93 [Feat] 댓글, 좋아요, 완료
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/controller/HomeController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardFileDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/board/model/Ddabong.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#97 Feat MG
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#98 [dev] 계시판 입력
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#99 후기 게시판 작성 완료
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#100 제네릭 수정
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_B.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_BLBL.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_BLCL.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_C.java
Labels: dev feature

#101 [Bug] 서버 빌드 버그 테스트 중
  build.gradle
Labels: bug

#102 [Feat] JWT 토큰 만료 시간 증가 36초 -> 30분
  src/main/java/com/ddabong/tripflow/TripFlowApplication.java
  src/main/java/com/ddabong/tripflow/config/SecurityConfig.java
  src/main/java/com/ddabong/tripflow/controller/MainController.java
  src/main/java/com/ddabong/tripflow/member/jwt/LoginFilter.java
Labels: dev feature

#104 해시태그 및 id 자동증가
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/HashDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_BLCL.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#106 [Dev] flask 요청 테스트
  src/main/java/com/ddabong/tripflow/chatbot/controller/RestReqController.java
Labels: dev feature

#108 시간 자동 저장 및 해시태그 저장
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/HashDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_Listid.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_SavePost.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#110 [Dev] 후기 작성 기능
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
  src/main/java/com/ddabong/tripflow/post/dao/IImageRepository.java
  src/main/java/com/ddabong/tripflow/post/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/post/dto/ImageDTO.java
  src/main/java/com/ddabong/tripflow/post/model/Image.java
  src/main/java/com/ddabong/tripflow/post/model/PostImage.java
  src/main/java/com/ddabong/tripflow/post/service/IImageService.java
  src/main/java/com/ddabong/tripflow/post/service/IPostImageService.java
  src/main/java/com/ddabong/tripflow/post/service/ImageService.java
  src/main/java/com/ddabong/tripflow/post/service/PostImageService.java
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/mapper/PostImageMapper.xml
Labels: dev feature

#111 [Dev] 댓글 작성 기능 추가
  src/main/java/com/ddabong/tripflow/comment/controller/WriteCommentController.java
  src/main/java/com/ddabong/tripflow/comment/dao/ICommentRepository.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentInfoDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/WriteCommentResponseDTO.java
  src/main/java/com/ddabong/tripflow/comment/model/Comment.java
  src/main/java/com/ddabong/tripflow/comment/service/CommentService.java
  src/main/java/com/ddabong/tripflow/comment/service/ICommentService.java
  src/main/java/com/ddabong/tripflow/image/dao/IImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IProfileImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dto/ImageDTO.java
  src/main/java/com/ddabong/tripflow/image/model/Image.java
  src/main/java/com/ddabong/tripflow/image/model/PostImage.java
  src/main/java/com/ddabong/tripflow/image/model/ProfileImage.java
  src/main/java/com/ddabong/tripflow/image/service/IImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IPostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IProfileImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ImageService.java
  src/main/java/com/ddabong/tripflow/image/service/PostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ProfileImageService.java
  src/main/java/com/ddabong/tripflow/member/dao/IMemberRepository.java
  src/main/java/com/ddabong/tripflow/member/service/IMemberService.java
  src/main/java/com/ddabong/tripflow/member/service/MemberService.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
  src/main/java/com/ddabong/tripflow/post/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/post/dao/IPostRepository.java
  src/main/java/com/ddabong/tripflow/post/service/IImageService.java
  src/main/java/com/ddabong/tripflow/post/service/IPostService.java
  src/main/java/com/ddabong/tripflow/post/service/PostService.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/PostImageMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ProfileImageMapper.xml
Labels: dev feature

#112 error 발생으로 #108 commit으로복구
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_Listid.java
  src/main/java/com/ddabong/tripflow/comment/controller/WriteCommentController.java
  src/main/java/com/ddabong/tripflow/comment/dao/ICommentRepository.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentInfoDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/WriteCommentResponseDTO.java
  src/main/java/com/ddabong/tripflow/comment/model/Comment.java
  src/main/java/com/ddabong/tripflow/comment/service/CommentService.java
  src/main/java/com/ddabong/tripflow/comment/service/ICommentService.java
  src/main/java/com/ddabong/tripflow/hashtag/dao/IHashtagJoinRepository.java
  src/main/java/com/ddabong/tripflow/hashtag/dao/IHashtagRepository.java
  src/main/java/com/ddabong/tripflow/hashtag/dto/HashtagJoinDTO.java
  src/main/java/com/ddabong/tripflow/hashtag/model/Hashtag.java
  src/main/java/com/ddabong/tripflow/hashtag/model/HashtagJoin.java
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagJoinService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/IHashtagJoinService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/IHashtagService.java
  src/main/java/com/ddabong/tripflow/image/dao/IImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IProfileImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dto/ImageDTO.java
  src/main/java/com/ddabong/tripflow/image/model/Image.java
  src/main/java/com/ddabong/tripflow/image/model/PostImage.java
  src/main/java/com/ddabong/tripflow/image/model/ProfileImage.java
  src/main/java/com/ddabong/tripflow/image/service/IImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IPostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IProfileImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ImageService.java
  src/main/java/com/ddabong/tripflow/image/service/PostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ProfileImageService.java
  src/main/java/com/ddabong/tripflow/member/dao/IMemberRepository.java
  src/main/java/com/ddabong/tripflow/member/service/IMemberService.java
  src/main/java/com/ddabong/tripflow/member/service/MemberService.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
  src/main/java/com/ddabong/tripflow/post/dao/IPostRepository.java
  src/main/java/com/ddabong/tripflow/post/dto/PostDTO.java
  src/main/java/com/ddabong/tripflow/post/dto/WritePostDTO.java
  src/main/java/com/ddabong/tripflow/post/dto/WritePostResponseDTO.java
  src/main/java/com/ddabong/tripflow/post/model/Post.java
  src/main/java/com/ddabong/tripflow/post/service/IPostService.java
  src/main/java/com/ddabong/tripflow/post/service/PostService.java
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/HashtagJoinMapper.xml
  src/main/resources/mapper/HashtagMapper.xml
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/PostImageMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ProfileImageMapper.xml
Labels: bug

#113 error 원인 mapper 발견 mapper 만 기존으로 변경
  src/main/java/com/ddabong/tripflow/comment/controller/WriteCommentController.java
  src/main/java/com/ddabong/tripflow/comment/dao/ICommentRepository.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/CommentInfoDTO.java
  src/main/java/com/ddabong/tripflow/comment/dto/WriteCommentResponseDTO.java
  src/main/java/com/ddabong/tripflow/comment/model/Comment.java
  src/main/java/com/ddabong/tripflow/comment/service/CommentService.java
  src/main/java/com/ddabong/tripflow/comment/service/ICommentService.java
  src/main/java/com/ddabong/tripflow/hashtag/dao/IHashtagJoinRepository.java
  src/main/java/com/ddabong/tripflow/hashtag/dao/IHashtagRepository.java
  src/main/java/com/ddabong/tripflow/hashtag/dto/HashtagJoinDTO.java
  src/main/java/com/ddabong/tripflow/hashtag/model/Hashtag.java
  src/main/java/com/ddabong/tripflow/hashtag/model/HashtagJoin.java
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagJoinService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/IHashtagJoinService.java
  src/main/java/com/ddabong/tripflow/hashtag/service/IHashtagService.java
  src/main/java/com/ddabong/tripflow/image/dao/IImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IProfileImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dto/ImageDTO.java
  src/main/java/com/ddabong/tripflow/image/model/Image.java
  src/main/java/com/ddabong/tripflow/image/model/PostImage.java
  src/main/java/com/ddabong/tripflow/image/model/ProfileImage.java
  src/main/java/com/ddabong/tripflow/image/service/IImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IPostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IProfileImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ImageService.java
  src/main/java/com/ddabong/tripflow/image/service/PostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ProfileImageService.java
  src/main/java/com/ddabong/tripflow/member/dao/IMemberRepository.java
  src/main/java/com/ddabong/tripflow/member/service/IMemberService.java
  src/main/java/com/ddabong/tripflow/member/service/MemberService.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
  src/main/java/com/ddabong/tripflow/post/dao/IPostRepository.java
  src/main/java/com/ddabong/tripflow/post/dto/PostDTO.java
  src/main/java/com/ddabong/tripflow/post/dto/WritePostDTO.java
  src/main/java/com/ddabong/tripflow/post/dto/WritePostResponseDTO.java
  src/main/java/com/ddabong/tripflow/post/model/Post.java
  src/main/java/com/ddabong/tripflow/post/service/IPostService.java
  src/main/java/com/ddabong/tripflow/post/service/PostService.java
Labels: bug

#118 [Bug] 충돌 복구
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/HashtagJoinMapper.xml
  src/main/resources/mapper/HashtagMapper.xml
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/PostImageMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ProfileImageMapper.xml
Labels: bug

#119 list 전체 조회 error 수정
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: bug

#120 [Dev] 내가 작성한 후기 게시글 목록 조회
  src/main/java/com/ddabong/tripflow/image/dao/IImageRepository.java
  src/main/java/com/ddabong/tripflow/image/dao/IPostImageRepository.java
  src/main/java/com/ddabong/tripflow/image/service/IImageService.java
  src/main/java/com/ddabong/tripflow/image/service/IPostImageService.java
  src/main/java/com/ddabong/tripflow/image/service/ImageService.java
  src/main/java/com/ddabong/tripflow/image/service/PostImageService.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowMyReviewListController.java
  src/main/resources/mapper/ImageMapper.xml
  src/main/resources/mapper/PostImageMapper.xml
Labels: dev feature

#122 [Dev] 챗봇 구현 중...
  build.gradle
  src/main/java/com/ddabong/tripflow/chatbot/config/AppConfig.java
  src/main/java/com/ddabong/tripflow/chatbot/config/WebClientConfig.java
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/dao/IChatLogRepository.java
  src/main/java/com/ddabong/tripflow/chatbot/model/ChatLog.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/java/com/ddabong/tripflow/chatbot/service/IChatLogService.java
  src/main/resources/mapper/ChatLogMapper.xml
Labels: dev feature

#123 [Bug] Cors 테스트
  src/main/java/com/ddabong/tripflow/post/controller/ShowDetailReviewController.java
Labels: bug

#124 [Dev] 챗봇 기능 구현 중 .... 사용자 나이 반영, [Bug] 원본 이미지 파일 이름 인코딩
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/member/dao/IMemberRepository.java
  src/main/java/com/ddabong/tripflow/member/service/IMemberService.java
  src/main/java/com/ddabong/tripflow/member/service/MemberService.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
  src/main/resources/mapper/MemberMapper.xml
Labels: bug, dev feature

#125 [Bug] 업로드 이미지 이름 공백, 특수문자 포함된 경우 오류 해결
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
Labels: bug

#126 [Bug] 해시태그 null 입력시 예외처리
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagService.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
Labels: bug

#127 [Dev] 채팅 시작 기능 구현
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/hashtag/service/HashtagService.java
Labels: dev feature

#128 jwt 토큰 사용변경, 좋아요 저장 및 변경기능 추가
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/CommentDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/MemberDTO.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_B.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_Listid.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_SaveComment.java
  src/main/java/com/ddabong/tripflow/board/dto/TestDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/GetBoardInfoService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/java/com/ddabong/tripflow/config/SecurityConfig.java
  src/main/java/com/ddabong/tripflow/member/jwt/LoginFilter.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#129 [Dev] 게시글 상세 조회시 좋아요 체크 여부 추가
  src/main/java/com/ddabong/tripflow/ddabong/dao/IDdabongRepository.java
  src/main/java/com/ddabong/tripflow/ddabong/service/DdabongService.java
  src/main/java/com/ddabong/tripflow/ddabong/service/IDdabongService.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowDetailReviewController.java
  src/main/java/com/ddabong/tripflow/post/dto/DetailReviewInfoDTO.java
  src/main/resources/mapper/DdabongMapper.xml
Labels: dev feature

#130 [Dev, Refactor] 챗봇 대화 기능 및 S3 URL 은닉화
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowDetailReviewController.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowMyReviewListController.java
  src/main/java/com/ddabong/tripflow/post/controller/WriteReviewController.java
Labels: dev feature, Refactor

#131 전체 조회 대표이미지 조회 및 필요데이더만 전송, 이미지 저장시 url 문제점 해결
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/BoardDTO_View.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO_AllList.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#132 좋아요 누른 게시물목록 출력
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
Labels: dev feature

#134 [Dev] 대화 내용 DB 저장 기능 추가 및 유저별 상태 저장
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/dao/IChatLogRepository.java
  src/main/java/com/ddabong/tripflow/chatbot/dto/UserStateDTO.java
  src/main/java/com/ddabong/tripflow/chatbot/model/ChatLog.java
  src/main/java/com/ddabong/tripflow/chatbot/model/ChatLogMapping.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/java/com/ddabong/tripflow/chatbot/service/IChatLogService.java
  src/main/resources/mapper/ChatLogMapper.xml
Labels: dev feature

#135 [Dev] 일정 생성 결과 저장 작업 시작
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#136 게시글 삭제
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/DeletePostDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#138 [Dev] /chat/start Get -> POST
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#139 게시글 수정
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/ResponseDTO.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#140 후기 이미지 수정
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#142 게시물 삭제 실패시 status 400 403으로 설절
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
Labels: bug

#143 [Dev] 챗봇 대화 기능
  src/main/java/com/ddabong/tripflow/chatbot/dto/UserStateDTO.java
  src/main/java/com/ddabong/tripflow/chatbot/model/ChatLog.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/java/com/ddabong/tripflow/chatbot/service/IChatLogService.java
  src/main/java/com/ddabong/tripflow/place/dao/IPlaceRepository.java
  src/main/java/com/ddabong/tripflow/place/model/Hotel.java
  src/main/java/com/ddabong/tripflow/place/model/Place.java
  src/main/java/com/ddabong/tripflow/place/model/Restaurant.java
  src/main/java/com/ddabong/tripflow/place/model/Tour.java
  src/main/java/com/ddabong/tripflow/place/service/IPlaceService.java
  src/main/java/com/ddabong/tripflow/place/service/PlaceService.java
  src/main/java/com/ddabong/tripflow/travel/dao/ITravelRepository.java
  src/main/java/com/ddabong/tripflow/travel/dto/TravelPlaceJoinDTO.java
  src/main/java/com/ddabong/tripflow/travel/dto/TravelSequenceSaveFormDTO.java
  src/main/java/com/ddabong/tripflow/travel/model/Travel.java
  src/main/java/com/ddabong/tripflow/travel/model/TravelPlaceJoin.java
  src/main/java/com/ddabong/tripflow/travel/service/ITravelService.java
  src/main/java/com/ddabong/tripflow/travel/service/TravelService.java
  src/main/resources/mapper/ChatLogMapper.xml
  src/main/resources/mapper/PlaceMapper.xml
  src/main/resources/mapper/TravelMapper.xml
Labels: dev feature

#145 [DEV} 일정생성 리턴
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#146 [Dev] 여행일정 결과 임시저장 및 validation 개발
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/resources/mapper/ChatLogMapper.xml
Labels: dev feature

#147 [Dev] validation 저장기능 개발중
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/resources/mapper/ChatLogMapper.xml
Labels: dev feature

#148 좋아요 누르면 추천 수 증가
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/java/com/ddabong/tripflow/board/dao/IBoardRepository.java
  src/main/java/com/ddabong/tripflow/board/dto/RecommendPlaceDTO.java
  src/main/java/com/ddabong/tripflow/board/model/Ddabong.java
  src/main/java/com/ddabong/tripflow/board/service/BoardService.java
  src/main/java/com/ddabong/tripflow/board/service/IBoardService.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#149 [DEV] 챗봇 validation
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#150 [Dev] GOOD-일정생성
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#151 [Dev] Good, Again, Other
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#152 [Dev] 일정 저장 기능 완료
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
Labels: dev feature

#153 [Dev] 나의 과거, 현재, 미래 일정정보 가져오기
  src/main/java/com/ddabong/tripflow/post/dto/TravelListResponseDTO.java
  src/main/java/com/ddabong/tripflow/travel/controller/LoadMyTravelSchedule.java
  src/main/java/com/ddabong/tripflow/travel/dao/ITravelRepository.java
  src/main/java/com/ddabong/tripflow/travel/dto/LoadTravelScheduleListDTO.java
  src/main/java/com/ddabong/tripflow/travel/dto/TravelDTO.java
  src/main/java/com/ddabong/tripflow/travel/service/ITravelService.java
  src/main/java/com/ddabong/tripflow/travel/service/TravelService.java
  src/main/resources/mapper/TravelMapper.xml
Labels: dev feature

#154 [Dev] 일정 상세 정보 조회 기능
  src/main/java/com/ddabong/tripflow/place/dao/IPlaceRepository.java
  src/main/java/com/ddabong/tripflow/place/dto/NameAndLatAndLon.java
  src/main/java/com/ddabong/tripflow/place/dto/PlaceDTO.java
  src/main/java/com/ddabong/tripflow/place/service/IPlaceService.java
  src/main/java/com/ddabong/tripflow/place/service/PlaceService.java
  src/main/java/com/ddabong/tripflow/travel/controller/LoadMyDetailTravelScheduleController.java
  src/main/java/com/ddabong/tripflow/travel/controller/LoadMyTravelScheduleController.java
  src/main/java/com/ddabong/tripflow/travel/dao/ITravelRepository.java
  src/main/java/com/ddabong/tripflow/travel/dto/DetailTravelResponseDTO.java
  src/main/java/com/ddabong/tripflow/travel/dto/LoadDetailTravelScheduleDTO.java
  src/main/java/com/ddabong/tripflow/travel/dto/TravelListResponseDTO.java
  src/main/java/com/ddabong/tripflow/travel/model/MergeTravelPlace.java
  src/main/java/com/ddabong/tripflow/travel/service/ITravelService.java
  src/main/java/com/ddabong/tripflow/travel/service/TravelService.java
  src/main/resources/mapper/PlaceMapper.xml
  src/main/resources/mapper/TravelMapper.xml
Labels: dev feature

#155 [Dev] 일정 상세 조회 경로 고도화
  src/main/java/com/ddabong/tripflow/place/dto/NameAndLatAndLon.java
  src/main/java/com/ddabong/tripflow/travel/controller/LoadMyDetailTravelScheduleController.java
  src/main/java/com/ddabong/tripflow/travel/dto/LoadDetailTravelScheduleDTO.java
Labels: dev feature

#157 [Dev] 후기 상세 조회 위경도 경로순으로 조회 기능 추가
  build.gradle
  src/main/java/com/ddabong/tripflow/chatbot/controller/ChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/controller/UpdateChatbotController.java
  src/main/java/com/ddabong/tripflow/chatbot/dao/IChatLogRepository.java
  src/main/java/com/ddabong/tripflow/chatbot/dto/UpdateScheduleResponseDTO.java
  src/main/java/com/ddabong/tripflow/chatbot/dto/UpdateUserStateDTO.java
  src/main/java/com/ddabong/tripflow/chatbot/service/ChatLogService.java
  src/main/java/com/ddabong/tripflow/chatbot/service/IChatLogService.java
  src/main/java/com/ddabong/tripflow/config/jasypt/EncryptConfig.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowDetailReviewController.java
  src/main/java/com/ddabong/tripflow/post/dto/DetailReviewInfoDTO.java
  src/main/resources/mapper/ChatLogMapper.xml
Labels: dev feature

#158 [Bug] 서버 실행
  src/main/java/com/ddabong/tripflow/chatbot/controller/UpdateChatbotController.java
Labels: bug

#159 좋아요 수정
  src/main/java/com/ddabong/tripflow/board/controller/BoardController.java
  src/main/resources/mapper/BoardMapper.xml
Labels: dev feature

#160 [Bug] 후기 경로 상세 조회 로그인 유저 id아닌 작성자 id를 받아야함
  src/main/java/com/ddabong/tripflow/chatbot/controller/UpdateChatbotController.java
  src/main/java/com/ddabong/tripflow/post/controller/ShowDetailReviewController.java
Labels: bug

#161 [Dev] 수정 챗봇
  src/main/java/com/ddabong/tripflow/chatbot/controller/UpdateChatbotController.java
Labels: dev feature
